Kunto/Kunto.Web/Controllers/DesignPatternsController.cs
using System.Web.Mvc;

namespace Kunto.Web.Controllers
{
    public class DesignPatternsController : Controller
    {
        public ActionResult Index()
        {
            return View("Patterns");
        }
    }
}

Kunto/Kunto.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Kunto.Web.Controllers
{
    /// <summary>
    /// </summary>
    public class HomeController : Controller
    {
        #region Public Methods and Operators

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult Index()
        {
            return View(HttpContext.Application["events"]);
        }

        #endregion
    }
}

Kunto/Kunto.Web/Controllers/Samples/ASPNETController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;

using Kunto.Web.Infrustructure.Samples;

namespace Kunto.Web.Controllers.Samples
{
    /// <summary>
    /// </summary>
    public class ASPNETController : Controller
    {
        #region Public Methods and Operators

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult CacheData()
        {
            return this.View((long?)this.HttpContext.Cache["pageLength"]);
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        [OutputCache(Duration = 30, Location = OutputCacheLocation.Server)]
        public ActionResult CachingContent()
        {
            Thread.Sleep(1000);

            int counterValue = AppStateHelper.IncrementAndGet(AppStateKeys.INDEX_COUNTER);

            Debug.WriteLine(string.Format("INDEX_COUNTER: {0}", counterValue));

            return View(counterValue);
        }

        /// <summary>
        /// </summary>
        /// <param name="country">
        /// </param>
        /// <returns>
        /// </returns>
        [HttpPost]
        public ActionResult CompleteForm(string country)
        {
            System.Diagnostics.Debug.WriteLine("Country: {0}", (object)country);

            // in a real application, this is where the call to create the
            // new user account would be
            this.ViewBag.Name = SessionStateHelper.Get(SessionStateKeys.NAME);
            this.ViewBag.Country = country;
            return this.View();
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult Events()
        {
            return this.View(this.HttpContext.Application["events"]);
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult Increment()
        {
            int currentValue = (int)AppStateHelper.Get(AppStateKeys.COUNTER, 0);
            AppStateHelper.Set(AppStateKeys.COUNTER, currentValue + 1);
            AppStateHelper.SetMultiple(new Dictionary<AppStateKeys, object>
                                           {
                                               {
                                                   AppStateKeys
                                                   .LAST_REQUEST_TIME, 
                                                   this.HttpContext
                                                       .Timestamp
                                               }, 
                                               {
                                                   AppStateKeys
                                                   .LAST_REQUEST_URL, 
                                                   this.Request
                                                       .RawUrl
                                               }
                                           });
            return this.RedirectToAction("StateData");
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult Modules()
        {
            var modules = this.HttpContext.ApplicationInstance.Modules;

            Tuple<string, string>[] data =
                modules.AllKeys.Select(
                    x =>
                    new Tuple<string, string>(x.StartsWith("__Dynamic") ? x.Split('_', ',')[3] : x, 
                        modules[x].GetType().Name)).OrderBy(x => x.Item1).ToArray();

            return View(data);
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public async Task<ActionResult> PopulateCache()
        {
            HttpResponseMessage result = await new HttpClient().GetAsync("http://apress.com");
            this.HttpContext.Cache["pageLength"] = result.Content.Headers.ContentLength;
            return this.RedirectToAction("CacheData");
        }

        /// <summary>
        /// </summary>
        /// <param name="name">
        /// </param>
        /// <returns>
        /// </returns>
        [HttpPost]
        public ActionResult ProcessFirstForm(string name)
        {
            System.Diagnostics.Debug.WriteLine("Name: {0}", (object)name);
            SessionStateHelper.Set(SessionStateKeys.NAME, name);
            return this.View("SecondForm");
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult Registration()
        {
            return this.View();
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult Samples()
        {
            return this.View();
        }

        /// <summary>
        /// </summary>
        /// <returns>
        /// </returns>
        public ActionResult StateData()
        {
            Dictionary<string, object> data = new Dictionary<string, object>();

            data.Add("Counter", AppStateHelper.Get(AppStateKeys.COUNTER, 0));
            IDictionary<AppStateKeys, object> stateData =
                AppStateHelper.GetMultiple(AppStateKeys.LAST_REQUEST_TIME, 
                    AppStateKeys.LAST_REQUEST_URL);

            foreach (AppStateKeys key in stateData.Keys){
                data.Add(Enum.GetName(typeof(AppStateKeys), key), stateData[key]);
            }

            return View(data);
        }

        #endregion
    }
}

Kunto/Kunto.Web/Views/ASPNET/Browser.cshtml
@{
    Layout = null;
}

<div class="panel panel-primary">
    <div class="panel-heading">Capabilities</div>
    <table class="table table-striped table-bordered">
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Browser</td>
            <td>@Request.Browser.Browser</td>
        </tr>
        <tr>
            <td>IsMobileDevice</td>
            <td>@Request.Browser.IsMobileDevice</td>
        </tr>
        <tr>
            <td>MobileDeviceManufacturer</td>
            <td>@Request.Browser.MobileDeviceManufacturer</td>
        </tr>
        <tr>
            <td>MobileDeviceModel</td>
            <td>@Request.Browser.MobileDeviceModel</td>
        </tr>
        <tr>
            <td>ScreenPixelsHeight</td>
            <td>@Request.Browser.ScreenPixelsHeight</td>
        </tr>
        <tr>
            <td>ScreenPixelsWidth</td>
            <td>@Request.Browser.ScreenPixelsWidth</td>
        </tr>
        <tr>
            <td>Version</td>
            <td>@Request.Browser.Version</td>
        </tr>
        @*  <tr>
            <td>CssColumn</td>
            <td>@Request.Browser["CssColumn"]</td>
        </tr>
        <tr>
            <td>CssFlexbox</td>
            <td>@Request.Browser["CssFlexbox"]</td>
        </tr>*@
    </table>
</div>

@Html.ActionLink("Got to Sate", "Increment", "ASPNET")

Kunto/Kunto.Web/Views/ASPNET/CacheData.cshtml
@model long?

@{
    Layout = null;
}

<div class="alert alert-info">
    @if (Model.HasValue)
    {
        @: Cached Data: @Model bytes
 }
    else
    {
        @: No Cached Data
 }
</div>
@using (Html.BeginForm("PopulateCache", "ASPNET"))
{
    <button class="btn btn-primary">Populate Cache</button>
}

Kunto/Kunto.Web/Views/ASPNET/CachingContent.cshtml
@model int

<div class="alert alert-info">
    The counter value: @Model
</div>
@Html.ActionLink("Update", "CachingContent", "ASPNET", new { @class = "btn btn-primary" })

Kunto/Kunto.Web/Views/ASPNET/CompleteForm.cshtml
<div class="panel panel-default">
    <div class="panel-heading">Registration Details</div>
    <table class="table table-striped">
        <tr>
            <th>Name</th>
            <td>@ViewBag.Name</td>
        </tr>
        <tr>
            <th>Country</th>
            <td>@ViewBag.Country</td>
        </tr>
    </table>
</div>

Kunto/Kunto.Web/Views/ASPNET/Events.cshtml
@model dynamic

@{
    ViewBag.Title = "ASP.NET Events";
    Layout = null;
}

<div class="panel panel-primary">
    <h5 class="panel-heading">Events</h5>
    <table class="table table-condensed table-striped">
        @foreach (string eventName in Model)
        {
            <tr>
                <td>@eventName</td>
            </tr>
        }
    </table>
</div>

Kunto/Kunto.Web/Views/ASPNET/Modules.cshtml
@model System.Tuple<string, string>[]

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Tuple<string, string> x in Model)
        {
            <tr>
                <td>@x.Item1</td>
                <td>@x.Item2</td>
            </tr>
        }
    </tbody>
</table>

Kunto/Kunto.Web/Views/ASPNET/Registration.cshtml
@using (Html.BeginForm("ProcessFirstForm", "ASPNET"))
{
    <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" name="name" placeholder="Enter name">
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
}

Kunto/Kunto.Web/Views/ASPNET/Samples.cshtml
@{
    ViewBag.Title = "ASP.NET Samples";
}
<div role="tabpanel">
    <ul class="nav nav-tabs" id="id-knt-tabpane-samples"  role="tablist">
        <li role="presentation" class="active"><a role="tab" data-toggle="tab" href="#id-aspnet-lifecycle-events">Life Cycle Events</a></li>
        <li role="presentation"><a role="tab" data-toggle="tab" href="#id-aspnet-request-properties">Request/Response Properties</a></li>
        <li role="presentation"><a role="tab" data-toggle="tab" href="#id-aspnet-default-modules">Default Modules</a></li>
        <li role="presentation"><a role="tab" data-toggle="tab" href="#id-aspnet-browser-capabilities">Browser Capabilities</a></li>
        <li role="presentation"><a role="tab" data-toggle="tab" href="#id-aspnet-statedata">State Data</a></li>
        <li role="presentation"><a role="tab" data-toggle="tab" href="#id-aspnet-registration">Session State</a></li>
        <li role="presentation"><a role="tab" data-toggle="tab" href="#id-aspnet-cache">Cache Data</a></li>
        <li role="presentation"><a role="tab" data-toggle="tab" href="#id-aspnet-cachecontent">Cache Content</a></li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="id-aspnet-lifecycle-events">
             @Html.Action("Events", "ASPNET")
        </div>
        <div  role="tabpanel" class="tab-pane" id="id-aspnet-request-properties">
            @Html.Partial("~/Views/ASPNET/_RequestResponseProperties.cshtml")
        </div>
        <div role="tabpanel" class="tab-pane" id="id-aspnet-default-modules">
            @Html.Action("Modules", "ASPNET")
        </div>
        <div  role="tabpanel" class="tab-pane" id="id-aspnet-browser-capabilities">
            @Html.Partial("~/Views/ASPNET/Browser.cshtml")
        </div>
        <div role="tabpanel" class="tab-pane" id="id-aspnet-statedata">
            @Html.Action("StateData", "ASPNET")
        </div>
        <div role="tabpanel" class="tab-pane" id="id-aspnet-registration">
            @Html.Action("Registration", "ASPNET")
        </div>
        <div role="tabpanel" class="tab-pane" id="id-aspnet-cache">
            @Html.Action("CacheData", "ASPNET")
        </div>
        <div role="tabpanel" class="tab-pane" id="id-aspnet-cachecontent">
             @Html.Action("CachingContent", "ASPNET")
        </div>
    </div>
</div>
<script>

    $('id-knt-tabpane-samples').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });

</script>

Kunto/Kunto.Web/Views/ASPNET/SecondForm.cshtml
@using (Html.BeginForm("CompleteForm", "ASPNET"))
{
    <div class="form-group">
        <label for="country">Country</label>
        <input class="form-control" name="country" placeholder="Enter country">
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
}

Kunto/Kunto.Web/Views/ASPNET/StateData.cshtml
@{
    Layout = null;
}

<div class="panel panel-primary">
    <div class="panel-heading">Data</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Property</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach (string key in Model.Keys)
            {
                <tr>
                    <td>@key</td>
                    <td>@Model[key]</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Kunto/Kunto.Web/Views/ASPNET/_RequestResponseProperties.cshtml
@model dynamic

@{
    ViewBag.Title = "Request/Response Properties";
}

<div class="panel panel-primary">
    <h5 class="panel-heading">Request Properties</h5>
    <table class="table table-condensed table-striped">
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>HttpMethod</td>
            <td>@Request.HttpMethod</td>
        </tr>
        <tr>
            <td>IsLocal</td>
            <td>@Request.IsLocal</td>
        </tr>
        <tr>
            <td>RawURL</td>
            <td>@Request.RawUrl</td>
        </tr>
        <tr>
            <td>Headers</td>
            <td>@Request.Headers.ToString()</td>
        </tr>
        <tr>
            <td>AcceptTypes</td>
            <td>@Request.AcceptTypes</td>
        </tr>
        <tr>
            <td>Browser</td>
            <td>@Request.Browser.Id</td>
        </tr>
        <tr>
            <td>ContentLength</td>
            <td>@Request.ContentLength</td>
        </tr>
        <tr>
            <td>UserAgent</td>
            <td>@Request.UserAgent</td>
        </tr>
        <tr>
            <td>UserHostAddress</td>
            <td>@Request.UserHostAddress</td>
        </tr>
        <tr>
            <td>UserHostName</td>
            <td>@Request.UserHostName</td>
        </tr>
        <tr>
            <td>UserLanguages</td>
            <td>@Request.UserLanguages</td>
        </tr>
    </table>
</div>

Kunto/Kunto.Web/Views/Dashboards/_Technical.cshtml
<div class="container-fluid knt-dashboard">
    <div class="row clearfix">
        <div class="col-md-12 knt-area knt-area-wrapper">
            Web UI
            <div class="row clearfix">
                <div class="col-md-3 knt-area">
                    <div>
                        <div class="knt-icon knt-dashboard-icon knt-html-icon"></div>
                        <div style="float: left; margin-left: 15px;">
                            <div>HTML/HTML5</div>
                            <div>2 years</div>
                        </div>
                    </div>
                    <div class="knt-icon knt-rate"></div>
                </div>
                <div class="col-md-3 knt-area">
                    <div>
                        <div class="knt-icon knt-dashboard-icon knt-css-icon"></div>
                        <div style="float: left; margin-left: 15px;">
                            <div>CSS</div>
                            <div>2 years</div>
                        </div>
                    </div>
                    <div class="knt-icon knt-rate"></div>
                </div>
                <div class="col-md-6 knt-area">
                    <div>
                        <div class="knt-icon knt-dashboard-icon  knt-js-icon"></div>
                        <div style="float: left; margin-left: 15px;">
                            <div>JavaScript</div>
                            <div>4 years</div>
                        </div>
                    </div>
                    <div class="knt-icon knt-rate"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 knt-area knt-area-wrapper">
            C#/.NET
            <div class="row clearfix">
                <div class="col-md-8 knt-area knt-area-wrapper">
                    <div class="row clearfix">
                        <a class="col-md-6 knt-area knt-area-wrapper" href="@Url.Action("Samples", "ASPNET")">
                            <div class="knt-area-2lvl">
                                <div class="knt-icon knt-dashboard-icon  knt-aspnet-icon"></div>
                                <div style="float: left; margin-left: 15px;">
                                    <div>ASP.NET</div>
                                    <div>1 year 6 months</div>
                                </div>
                            </div>
                            <div>
                                <div class="knt-icon knt-rate"></div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 knt-area">
                                    <div class="knt-icon knt-dashboard-icon  knt-aspmvc-icon"></div>
                                    <div style="float: left; margin-left: 15px;">
                                        <div>ASP.NET MVC</div>
                                        <div>1 year 6 months</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 knt-area">
                                    <div>
                                        <div class="knt-icon knt-dashboard-icon  knt-webapi-icon"></div>
                                        <div style="float: left; margin-left: 15px;">
                                            <div>WEB API</div>
                                            <div>2 years</div>
                                        </div>
                                    </div>
                                    <div class="knt-icon knt-rate"></div>
                                </div>
                            </div>
                        </a>
                        <div class="col-md-6 knt-area knt-area-wrapper">
                            <div class="row clearfix">
                                <div class="col-md-12 knt-area">
                                    <div>
                                        <div class="knt-icon knt-dashboard-icon  knt-silverlight-icon"></div>
                                        <div style="float: left; margin-left: 15px;">
                                            <div>Silverlight</div>
                                            <div>4 years</div>
                                        </div>
                                    </div>
                                    <div class="knt-icon knt-rate"></div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 knt-area">
                                    WPF
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 knt-area">
                                    Win Forms
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix">
                        <div class="col-md-12 knt-area knt-area-wrapper">
                            ADO.NET
                                <div class="row clearfix">
                                    <div class="col-md-12 knt-area">
                                        Entity Framework
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 knt-area knt-area-wrapper">
                    .NET Libs and Frameworks
                    <div class="row clearfix">
                        <div class="col-md-12 knt-area">
                            PRISM
                        </div>
                    </div>
                    <div class="row clearfix">
                        <div class="col-md-12 knt-area">
                            Enterprise Library
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 knt-area knt-area-wrapper">
            SQL
            <div class="row clearfix">
                <div class="col-md-6 knt-area">
                    MS SQL
                </div>
                <div class="col-md-6 knt-area">
                    MySql
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 knt-area knt-area-wrapper">
            Architecture
            <div class="row clearfix">
                <div class="col-md-6 knt-area">
                    <a href="@Url.Action("Index", "DesignPatterns")">
                        Design Patterns
                    </a>
                </div>
                <div class="col-md-6 knt-area">
                    S.O.L.I.D.
                </div>
                <div class="col-md-6 knt-area">
                    Enterprise Patterns
                </div>
                <div class="col-md-6 knt-area">
                    Unit of Work
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
    });
</script>

Kunto/Kunto.Web/Views/DesignPatterns/Patterns.cshtml
<script>
    var designPatternsApp = angular.module('designPatternsApp', []);
    var baseApiUrl = 'http://localhost/Kunto.Web/api/';
</script>

<script src="~/AppScripts/designPatterns/designPatternsService.js"></script>
<script src="~/AppScripts/designPatterns/designPatternsController.js"></script>

<div ng-app="designPatternsApp">
    <div ng-controller="designPatternsController">
        <ul>
            <li ng-repeat="pattern in patterns">
                <span>{{pattern.name}}</span>
                <p>{{pattern.id}}</p>
            </li>
        </ul>
    </div>
</div>

Kunto/Kunto.Web/Views/Home/Index.cshtml
<div class="container-fluid">
    <ul id="id-dashboards-slider">
        <li class="knt-dashboard">
            <h4 class="knt-title">Languages and Technologies Dashboard</h4>
            @Html.Partial("~/Views/Dashboards/_Technical.cshtml")
        </li>
        <li>
            <h4 class="knt-title">Skills Dashboard</h4>
        </li>
        <li>
            <h4 class="knt-title">Interests Dashboard</h4>
        </li>
        <li>
            <h4 class="knt-title">Foreign Languages Dashboard</h4>
        </li>
    </ul>
</div>

<script>
    $(document).ready(function () {
        $('#id-dashboards-slider').bxSlider();
    });
</script>


Kunto/Kunto.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <title>IT Guru Builder</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootswatch.min.css" rel="stylesheet" />
    <link href="~/Content/application/kunto.css" rel="stylesheet" />
    <link href="~/Content/application/kunto-theme.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-2.1.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.bxslider.min.js"></script>

    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-route.min.js"></script>
    <script src="~/Scripts/angular-resource.min.js"></script>

    <link href="~/Content/jquery.bxslider.css" rel="stylesheet" />
</head>
<body class="container-fluid">
    <div class="knt-app col-xs-12">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand" style="font-weight: bold">
                        @Html.ActionLink(" ", "index", "home", null, new { @class = "knt-icon knt-logo" })
                        <span style="font-weight: bold; line-height: 1.4em;">IT Guru Builder</span>
                    </div>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Resume</a></li>
                        <li><a href="#">Tasks Scheduler</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User Menu <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Login</a></li>
                                <li><a href="#">Register</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Create Profile</a></li>
                                <li><a href="#">Settings</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
        @RenderBody()
    </div>
</body>
</html>